local function read_license_key()
  local key_file = vim.fn.expand '~/.intelephense.key'
  local file = io.open(key_file, 'r')
  if file then
    local key = file:read '*l' -- Read first line
    file:close()
    return key
  end
  return nil
end

return {
  {
    'nvim-treesitter/nvim-treesitter',
    build = ':TSUpdate',
    config = function()
      require('nvim-treesitter.configs').setup {
        ensure_installed = { 'lua', 'php', 'javascript', 'html', 'css', 'scss' },
        auto_install = true,
        highlight = { enable = true },
      }
    end,
  },
  {
    'saghen/blink.cmp',
  },
  {
    'jose-elias-alvarez/typescript.nvim',
  },
  {
    'neovim/nvim-lspconfig',
    config = function()
      vim.lsp.config.ts_ls = {}
      vim.lsp.config.jsonls = {}
      vim.lsp.config.gopls = {}
      vim.lsp.config.sqls = {}
      vim.lsp.config.cssls = {}
      vim.lsp.config.somesass_ls = {}
      vim.lsp.config.css_variables = {}
      vim.lsp.config.lua_ls = {}
      vim.lsp.config.html = {}

      vim.lsp.config.tailwindcss = {
        filetypes = { 'html', 'css', 'javascript', 'typescript', 'php' },
      }

      vim.lsp.config.intelephense = {
        settings = {
          intelephense = {
            licenseKey = read_license_key(),
            files = {
              maxSize = 1000000,
            },
            storagePath = '/tmp/intelephense',
            stubs = {
              'amqp',
              'apache',
              'apcu',
              'bcmath',
              'blackfire',
              'bz2',
              'calendar',
              'cassandra',
              'com_dotnet',
              'Core',
              'couchbase',
              'crypto',
              'ctype',
              'cubrid',
              'curl',
              'date',
              'dba',
              'decimal',
              'dom',
              'ds',
              'enchant',
              'Ev',
              'event',
              'exif',
              'fann',
              'FFI',
              'ffmpeg',
              'fileinfo',
              'filter',
              'fpm',
              'ftp',
              'gd',
              'gearman',
              'geoip',
              'geos',
              'gettext',
              'gmagick',
              'gmp',
              'gnupg',
              'grpc',
              'hash',
              'http',
              'ibm_db2',
              'iconv',
              'igbinary',
              'imagick',
              'imap',
              'inotify',
              'interbase',
              'intl',
              'json',
              'judy',
              'ldap',
              'leveldb',
              'libevent',
              'libsodium',
              'libxml',
              'lua',
              'lzf',
              'mailparse',
              'mapscript',
              'mbstring',
              'mcrypt',
              'memcache',
              'memcached',
              'meminfo',
              'meta',
              'ming',
              'mongo',
              'mongodb',
              'mosquitto-php',
              'mqseries',
              'msgpack',
              'mssql',
              'mysql',
              'mysql_xdevapi',
              'mysqli',
              'ncurses',
              'newrelic',
              'oauth',
              'oci8',
              'odbc',
              'openssl',
              'parallel',
              'Parle',
              'pcntl',
              'pcov',
              'pcre',
              'pdflib',
              'PDO',
              'pdo_ibm',
              'pdo_mysql',
              'pdo_pgsql',
              'pdo_sqlite',
              'pgsql',
              'Phar',
              'phpdbg',
              'posix',
              'pspell',
              'pthreads',
              'radius',
              'rar',
              'rdkafka',
              'readline',
              'recode',
              'redis',
              'Reflection',
              'regex',
              'rpminfo',
              'rrd',
              'SaxonC',
              'session',
              'shmop',
              'SimpleXML',
              'snmp',
              'soap',
              'sockets',
              'sodium',
              'solr',
              'SPL',
              'SplType',
              'SQLite',
              'sqlite3',
              'sqlsrv',
              'ssh2',
              'standard',
              'stats',
              'stomp',
              'suhosin',
              'superglobals',
              'svn',
              'sybase',
              'sync',
              'sysvmsg',
              'sysvsem',
              'sysvshm',
              'tidy',
              'tokenizer',
              'uopz',
              'uv',
              'v8js',
              'wddx',
              'win32service',
              'winbinder',
              'wincache',
              'wordpress',
              'xcache',
              'xdebug',
              'xhprof',
              'xml',
              'xmlreader',
              'xmlrpc',
              'xmlwriter',
              'xsl',
              'xxtea',
              'yaf',
              'yaml',
              'yar',
              'zend',
              'Zend OPcache',
              'ZendCache',
              'ZendDebugger',
              'ZendUtils',
              'zip',
              'zlib',
              'zmq',
              'zookeeper',
            },
          },
        },
      }

      vim.lsp.config.eslint = {}

      vim.lsp.enable {
        'ts_ls',
        'jsonls',
        'gopls',
        'sqls',
        'cssls',
        'somesass_ls',
        'css_variables',
        'lua_ls',
        'html',
        'tailwindcss',
        'intelephense',
        'eslint',
      }
    end,
  },
}
