local stubs = {
	-- Standard PHP + WP ecosystem
	"random",
	"apache",
	"bcmath",
	"bz2",
	"calendar",
	"com_dotnet",
	"Core",
	"ctype",
	"curl",
	"date",
	"dba",
	"dom",
	"enchant",
	"exif",
	"FFI",
	"fileinfo",
	"filter",
	"fpm",
	"ftp",
	"gd",
	"gettext",
	"gmp",
	"hash",
	"iconv",
	"imap",
	"intl",
	"json",
	"ldap",
	"libxml",
	"mbstring",
	"meta",
	"mysqli",
	"oci8",
	"odbc",
	"openssl",
	"pcntl",
	"pcre",
	"PDO",
	"pdo_ibm",
	"pdo_mysql",
	"pdo_pgsql",
	"pdo_sqlite",
	"pgsql",
	"Phar",
	"posix",
	"pspell",
	"readline",
	"Reflection",
	"session",
	"shmop",
	"SimpleXML",
	"snmp",
	"soap",
	"sockets",
	"sodium",
	"SPL",
	"sqlite3",
	"standard",
	"superglobals",
	"sysvmsg",
	"sysvsem",
	"sysvshm",
	"tidy",
	"tokenizer",
	"xml",
	"xmlreader",
	"xmlrpc",
	"xmlwriter",
	"xsl",
	"Zend OPcache",
	"zip",
	"zlib",
	-- WordPress
	"wordpress",
	"woocommerce",
	"acf-pro",
	"wordpress-globals",
	"wp-cli",
	"genesis",
}

return {
	cmd = {
		"intelephense",
		"--stdio",
	},
	filetypes = { "php", "blade" },
	root_markers = { ".git", "composer.json", "index.php" },
	settings = {
		intelephense = {
			stubs = stubs,
			environment = {
				includePaths = {
					-- vim.fn.expand("~/.config/nvim/lua/vendor/php-stubs/wordpress-stubs"),
					-- Add cwd vendor and public directories
					vim.fn.getcwd() .. "/vendor/",
					vim.fn.getcwd() .. "/public/",
					-- "vendor/",
					-- "public/",
				},
			},
			files = {
				maxSize = 5000000,
				associations = {
					"**/*.php",
					"**/*.blade.php",
					-- vim.fn.expand("~/.config/nvim/lua/vendor/php-stubs/wordpress-stubs/wordpress.php"),
				},
				exclude = {},
			},
			format = {
				braces = "k&r",
			},
		},
	},
}
