local stubs = {
  'random',
  'apache',
  'bcmath',
  'bz2',
  'calendar',
  'com_dotnet',
  'Core',
  'ctype',
  'curl',
  'date',
  'dba',
  'dom',
  'enchant',
  'exif',
  'FFI',
  'fileinfo',
  'filter',
  'fpm',
  'ftp',
  'gd',
  'gettext',
  'gmp',
  'hash',
  'iconv',
  'imap',
  'intl',
  'json',
  'ldap',
  'libxml',
  'mbstring',
  'meta',
  'mysqli',
  'oci8',
  'odbc',
  'openssl',
  'pcntl',
  'pcre',
  'PDO',
  'pdo_ibm',
  'pdo_mysql',
  'pdo_pgsql',
  'pdo_sqlite',
  'pgsql',
  'Phar',
  'posix',
  'pspell',
  'readline',
  'Reflection',
  'session',
  'shmop',
  'SimpleXML',
  'snmp',
  'soap',
  'sockets',
  'sodium',
  'SPL',
  'sqlite3',
  'standard',
  'superglobals',
  'sysvmsg',
  'sysvsem',
  'sysvshm',
  'tidy',
  'tokenizer',
  'xml',
  'xmlreader',
  'xmlrpc',
  'xmlwriter',
  'xsl',
  'Zend OPcache',
  'zip',
  'zlib',
  -- ✅ WordPress-specific
  'wordpress',
  'woocommerce',
  'acf-pro',
  'wordpress-globals',
  'wp-cli',
  'genesis',
}

return function(lspconfig)
  lspconfig.intelephense.setup {
    init_options = {
      licenceKey = os.getenv 'INTELEPHENSE_LICENSE',
    },
    settings = {
      intelephense = {
        stubs = stubs,
        environment = {
          includePaths = {
            'vendor',
            'public/',
          },
        },
        files = {
          maxSize = 5000000,
          associations = { '**/*.php' },
          exclude = {}, -- don't exclude anything
        },
        format = {
          braces = 'k&r',
        },
      },
    },
  }
end
