-- Load our LSPs :)
vim.lsp.enable("luals")
vim.lsp.enable("intelephense")
-- vim.lsp.enable("html")
vim.lsp.enable("cssls")
vim.lsp.enable("tailwindcss")
vim.lsp.enable("gopls")
vim.lsp.enable("zig")
vim.lsp.enable("js")
